### ISSUE TITLE
Treatment of Children

### ISSUE THREAD

**Issue by Jador** [Jador/react-hyperscript-helpers#10]
Previously, you were not required to use an array if you had a single child that was a string. Due to a convenient mistake on my part you could also do this with a component.

As of the changes I made yesterday (#4), this now works for numbers as well. However, you are now required to use an array when you have a single component as a child.

I know different hyperscripters have different opinions on whether or not children should always be an array. I want to get a pulse on how those using this lib feel on the issue before making a change.

Personally, I kind of like how this has shaken out. It seems like if you only have a single primitive child that the component is pretty simple and it might be nice to just say 'bob' and be done with it. Whereas, if you have a single component being forced to use the brackets could result in cleaner code.

Thoughts?

**Comment by kjr247** [comment]
Perhap I'll leave this here for anyone interested? @reqshark @mlmorg @tetsuo @jessy1092 @neurosnap @LittleBrainz @kumavis

**Comment by mlmorg** [comment]
The two arguments I've discussed with folks on allowing args vs. always using an array for children is consistency/cleanliness and optimization. While consistency/cleanliness of code can be subjective, there is a definitely a de-optimization when you use `arguments`, `slice()`, etc. which would be required to support this use-case. See https://github.com/mlmorg/react-hyperscript/pull/1#discussion_r18723100 and https://github.com/mlmorg/react-hyperscript/issues/7.

It would probably be worth doing a performance test in a large app (with universal rendering) to get an idea if the de-optimization is actually a problem. In the end, I just left the issue open and never decided what to do :)

**Comment by neurosnap** [comment]
In the midst of looking at all the different hyperscript helpers for react I ended up writing my own library to better understand the intricacies of interfacing with `React.createElement`.  The library I wrote looks similar to this one and requires children to be in an array with the exception of strings.

https://github.com/neurosnap/react-dom-hyperscript

I personally like the consistency of using arrays for any components and it doesn't really clutter the code too much.

**Comment by Jador** [comment]
@neurosnap, @mlmorg thank you for your thoughts on the matter.

@mlmorg I have lurked your issues for some time :) Always a good source of information.

I think I'll revise the OP with code examples of what we're talking about, so that it is clearer to those who come later.

I have been thinking about trying to get hyperscripters together not so much to form a standards body, I think there is plenty of room for api differences, but to share information and to increase awareness (without any further [JSX bashing](https://medium.com/@jador/jsx-4b978fbeb290) lol). 

What do you guys think? Good idea, bad idea? Too small of an issue to really worry about?

**Comment by neurosnap** [comment]
I think increasing awareness is a great idea and the best way to do that at this point is by increasing the documentation overall for this library.  It seems bizarre to say that we need to prove to the React community that simply using javascript is the better approach, but this is the ecosystem we live in ... for now.

The one issue I am personally going to be dealing with in the not-so-distant future is on-boarding other developers into a non-JSX react world.  Some of them have experience with JSX and some are coming into React fresh, untainted.  I would love to see this library turn into the go-to source for the non-JSX world of React and I'm happy to help where I can.

**Comment by Jador** [comment]
I agree, documentation is key. And I am very appreciative of your contributions on that front. Perhaps it would be good to have a gh-pages for the project?

Would love to hear your experience training up those familiar with jsx. I've had "fun" with that lol
