### ISSUE TITLE
event handlers

### ISSUE THREAD

**Issue by brucou** [Jador/react-hyperscript-helpers#26]
Simple question : how to add event handlers through the hyperscript helpers. I naively tried : 

`h(Counter, { count, onClick: trigger(BUTTON_CLICKED) }, [])`

but that failed lamentably

**Comment by Jador** [comment]
Can you link a codesandbox reproducing?

**Comment by brucou** [comment]
no need I figured it out, it is a beginner mistake. 

This works `h('div', { count, onClick: trigger(BUTTON_CLICKED) }, [])` but this does not : `h(Counter, { count, onClick: trigger(BUTTON_CLICKED) }, [])` because you cannot put event handlers on react component. You have to put the event handler on a DOM element... The `onClick` passed to the component is a property not an even handler.
