### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by matheusml** [Jador/react-hyperscript-helpers#9]
What about adding eslint to project and a new npm script to lint it before generating a new build?

**Comment by Jador** [comment]
You've got it. I'll probably adopt the one used by the reactjs/rackt community for the sake of consistency unless anyone has a better idea.

**Comment by matheusml** [comment]
Airbnb is a default choice, but since it's a react project, it's fair to use reactjs/rackt.

**Comment by Jador** [comment]
Went with airbnb with a couple of small personal preference tweaks
